apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-app-config
  namespace: messaging
data:
  SERVER_PORT: "8080"
  WS_PORT: "8081"
  DB_NAME: "messaging_app"
  KAFKA_TOPIC: "messages"
  KAFKA_BROKERS: "kafka-bootstrap.messaging.svc.cluster.local:9092"
  REDIS_URL: "redis-cluster.messaging.svc.cluster.local:6379"
  PROMETHEUS_PORT: "9091"
  ACCESS_TOKEN_TTL: "15"
  REFRESH_TOKEN_TTL: "7"
  CORS_ALLOWED_ORIGINS: "https://app.example.com"
  REFRESH_COOKIE_NAME: "connectify_refresh"
  COOKIE_DOMAIN: ".example.com"
  COOKIE_SECURE: "true"
  STORAGE_BUCKET: "connectify-uploads"
  STORAGE_USE_SSL: "false"
  STORAGE_PUBLIC_URL: "https://cdn.example.com"
  STORAGE_ENDPOINT: "http://minio.messaging.svc.cluster.local:9000"
