apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app
  labels:
    app: messaging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
      - name: messaging-app
        image: connectify/messaging-app:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: messaging-app-config
        - secretRef:
            name: messaging-app-secrets
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: connectify/user-service:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: user-service-config
        - secretRef:
            name: user-service-secrets
        ports:
        - containerPort: 9083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-service
  labels:
    app: story-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-service
  template:
    metadata:
      labels:
        app: story-service
    spec:
      containers:
      - name: story-service
        image: connectify/story-service:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: story-service-config
        - secretRef:
            name: story-service-secrets
        ports:
        - containerPort: 9097
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  labels:
    app: events-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: connectify/events-service:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: events-service-config
        - secretRef:
            name: events-service-secrets
        ports:
        - containerPort: 9096
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-service
  labels:
    app: marketplace-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketplace-service
  template:
    metadata:
      labels:
        app: marketplace-service
    spec:
      containers:
      - name: marketplace-service
        image: connectify/marketplace-service:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: marketplace-service-config
        - secretRef:
            name: marketplace-service-secrets
        ports:
        - containerPort: 9095
          name: grpc
        - containerPort: 8087
          name: http
