apiVersion: v1
kind: Secret
metadata:
  name: messaging-app-secrets
type: Opaque
stringData:
  JWT_SECRET: "change-me"
  REDIS_PASS: ""
  MONGO_USER: ""
  MONGO_PASSWORD: ""
  STORAGE_ACCESS_KEY: "minioadmin"
  STORAGE_SECRET_KEY: "minioadmin"
  NEO4J_PASSWORD: "connectify"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
stringData:
  JWT_SECRET: "change-me"
  REDIS_PASS: ""
  NEO4J_PASSWORD: "connectify"
---
apiVersion: v1
kind: Secret
metadata:
  name: story-service-secrets
type: Opaque
stringData:
  JWT_SECRET: "change-me"
---
apiVersion: v1
kind: Secret
metadata:
  name: events-service-secrets
type: Opaque
stringData:
  JWT_SECRET: "change-me"
  REDIS_PASS: ""
  STORAGE_ACCESS_KEY: "minioadmin"
  STORAGE_SECRET_KEY: "minioadmin"
---
apiVersion: v1
kind: Secret
metadata:
  name: feed-service-secrets
type: Opaque
stringData:
  REDIS_PASS: ""
  NEO4J_PASSWORD: "connectify"
---
apiVersion: v1
kind: Secret
metadata:
  name: marketplace-service-secrets
type: Opaque
stringData:
  CASSANDRA_PASSWORD: "cassandra"
