apiVersion: v1
kind: Service
metadata:
  name: messaging-app
  labels:
    app: messaging-app
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: messaging-app
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
  - port: 9083
    name: grpc
    targetPort: 9083
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: story-service
  labels:
    app: story-service
spec:
  ports:
  - port: 9097
    name: grpc
    targetPort: 9097
  selector:
    app: story-service
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  labels:
    app: events-service
spec:
  ports:
  - port: 9096
    name: grpc
    targetPort: 9096
  selector:
    app: events-service
---
apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  labels:
    app: marketplace-service
spec:
  ports:
  - port: 9095
    name: grpc
    targetPort: 9095
  selector:
    app: marketplace-service
